platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: e34a96a0963fee6d6bf50f6fc184797014464719

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: 065639a0a76c5f7c564509b8fd8b64f7949da4f5

- name: Ubuntu
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 90141766b9a1aa03cded820703c5d7f3e1d86f34

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: feature/smp
  commit: 63f2fc1f43a9a330a601bc51e1b4f639a09c618d

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: master
  commit: 03eac26fc47c09bcf7b51dd01c423c4880c8a99f

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 3132855d1873ce065059e3647be58f6b608c3a1f

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 53b61a46c27406623cdf7e727a2958aca98a1cda
